//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFacturacion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FacturacionMethods")]
    public interface FacturacionMethods {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/ValidateCredentials", ReplyAction="http://tempuri.org/FacturacionMethods/ValidateCredentialsResponse")]
        bool ValidateCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/ValidateCredentials", ReplyAction="http://tempuri.org/FacturacionMethods/ValidateCredentialsResponse")]
        System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturacionMethodsChannel : ClientFacturacion.ServiceReference1.FacturacionMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturacionMethodsClient : System.ServiceModel.ClientBase<ClientFacturacion.ServiceReference1.FacturacionMethods>, ClientFacturacion.ServiceReference1.FacturacionMethods {
        
        public FacturacionMethodsClient() {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionMethodsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateCredentials(string username, string password) {
            return base.Channel.ValidateCredentials(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string username, string password) {
            return base.Channel.ValidateCredentialsAsync(username, password);
        }
    }
}
